# -*- coding: utf-8 -*-
"""Untitled66.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1po1oSqcp2_1vKscw8zd_JgGR_mEdEcIe
"""

import numpy as np
import gym

if not hasattr(np,"bool8"):
    np.bool8 = np.bool_

env = gym.make('FrozenLake-v1')

env.observation_space.n

lr           = 0.8
y            = 0.95
num_episodes = 2000
j = 0

jList = []
rList = []

Q = np.zeros( [env.observation_space.n, env.action_space.n] )
Q.shape

stepsList    = [0.0005]
success_list = [0.0005]


test_games = 100

for i in range(test_games):
    s = env.reset()
    s = s
    j = 0
    while j < 1000:


        a = np.argmax(  Q[s,:]  )


        s1, r, d, _ = env.step(a)

        if d == True and r == 0:
             r = -1

        s = s1
        j = j + 1

        if d == True:
            break

    if d == True and r > 0:
        success_list.append(1)
    else:
        success_list.append(0)
    stepsList.append(j)

sum( success_list ) / 100

sum( stepsList ) / 100

